blog/urls.py
from django.urls import path
from .views import PostListView, PostDetailView, PostCreate, PostUpdate, PostDelete

app_name = 'blog'

urlpatterns = [
    path('', PostListView.as_view(), name='list'),
    path('create/', PostCreate.as_view(), name='create'),
    path('<slug>/', PostDetailView.as_view(), name='detail'),
    path('<slug>/update/', PostUpdate.as_view(), name='update'),
    path('<slug>/delete/', PostDelete.as_view(), name='delete'),
]

events/urls.py
from django.urls import path
from .views import EventListView, EventDetailView, EventCreate, EventUpdate, EventDelete

app_name = 'events'

urlpatterns = [
    path('', EventListView.as_view(), name='list'),
    path('create/', EventCreate.as_view(), name='create'),
    path('<slug>/', EventDetailView.as_view(), name='detail'),
    path('<slug>/update/', EventUpdate.as_view(), name='update'),
    path('<slug>/delete/', EventDelete.as_view(), name='delete'),
]

instructors/urls.py
from django.urls import path
from .views import login_view, logout_view, signup, become_instructor

app_name='auth'

urlpatterns = [
    path('login/', login_view, name='login'),
    path('signup/', signup, name='signup'),
    path('logout/', logout_view, name='logout'),
    
    path('become-instructor/', become_instructor, name='become_instructor'),
]

courses/models.py
from django.conf import settings
from django.db import models
from django.contrib.contenttypes.fields import GenericRelation
from django.utils.text import slugify
from django.db.models.signals import post_save
from django.urls import reverse

from instructors.models import Instructor
from comments.models import Comment
from tags.models import Tag
from membership.models import Membership
from django.contrib.contenttypes.models import ContentType
# from rating.models import Rate

from moviepy.editor import VideoFileClip
import datetime
from time import strftime
from time import gmtime
from django.db.models import Sum

import math

SKILL_LEVEL = [
    ('all', 'All level'),
    ('beginner', 'Beginner'),
    ('intermediate', 'Intermediate'),
    ('advanced', 'Advanced'),
]




def preview_video_upload(instance, filename):
    return f'courses/{instance.title}/{instance.title}_{filename}'

def lesson_video_upload(instance, filename):
    return f'courses/lessons/{instance.title}/{instance.title}_{filename}'

def category_image_upload(instance, filename):
    return f'categories/{instance.name}/{instance.name}_{filename}'


class Category(models.Model):
    name = models.CharField(max_length=50)
    slug = models.SlugField(blank=True, null=True)
    image = models.ImageField(upload_to=category_image_upload)

    class Meta:
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('courses:category', kwargs={'slug': self.slug})

class Course(models.Model):
    title                       = models.CharField(max_length=100)
    slug                        = models.SlugField(blank=True, null=True)
    author                      = models.ForeignKey(Instructor, on_delete=models.CASCADE)
    price                       = models.DecimalField(decimal_places=2, max_digits=10)
    discount                    = models.DecimalField(decimal_places=2, max_digits=10, blank=True, null=True)
    duration                    = models.IntegerField(default=0, help_text="Type the number of minutes", blank=True, null=True)
    full_lifetime_access        = models.BooleanField(default=True)
    assignments                 = models.BooleanField(default=True)
    Certificate_of_completion   = models.BooleanField(default=True)
    preview                     = models.FileField(verbose_name="Course Video Preview", upload_to=preview_video_upload, blank=True, null=True)
    thumbnail                   = models.FileField(verbose_name="Course Thumbnial Image", upload_to=preview_video_upload)
    overview                    = models.TextField()
    description                 = models.TextField()
    what_will_learn             = models.TextField(help_text="Separate them by comman and space.")
    requirements                = models.TextField(help_text="Separate them by comman and space.")
    Skill_level                 = models.CharField(choices=SKILL_LEVEL, default='All Level', max_length=20)
    Language                    = models.CharField(max_length=100)
    best_seller                 = models.BooleanField(default=False)
    tags                        = GenericRelation(Tag)
    comments                    = GenericRelation(Comment)
    enrolled                    = models.PositiveIntegerField(default=0)
    allowed_memberships         = models.ManyToManyField(Membership, default="Free")
    category                    = models.ManyToManyField(Category)
    views                       = models.PositiveIntegerField(default=0)
    total_points                = models.PositiveIntegerField(null=True, blank=True, default=1)
    avg_points                  = models.PositiveIntegerField(null=True, blank=True, default=1)
    total_rates                 = models.PositiveIntegerField(null=True, blank=True, default=1)
    timestamp                   = models.DateTimeField(auto_now_add=True)
    updated                     = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('courses:detail', kwargs={'slug': self.slug})

    @property
    def get_rating(self):
        av = self.avg_points / self.total_points * 100
        result = "{:.1f}".format(float(av / 20))
        return float(result)

    @property
    def get_rates(self):
        av = self.avg_points / self.total_points * 100
        result = "{:.1f}".format(float(av / 20))
        r = math.floor(float(result))
        return [i for i in range(int(r))]
    
    @property
    def get_remainder(self):
        av = self.avg_points / self.total_points * 100
        result = "{:.1f}".format(float(av / 20))
        r = math.floor(float(result))
        total = 0
        for i in range(5):
            if int(r) < 5:
                total+=1
                r+=1
        return [i for i in range(int(total)) ]
        

    @property
    def get_duration(self):
        return strftime("%H:%M:%S", gmtime(float(self.duration)))

    @property
    def get_duration_hours(self):
        return strftime("%H", gmtime(float(self.duration)))

    @property
    def get_lessons_count(self):
        total = 0
        for chapter in self.chapter_set.all():
            total += int(chapter.lesson_set.all().count())
        return int(total)


    @property
    def get_price(self):
        if self.discount:
            return self.discount
        return self.price
    
    @property
    def comments_count(self):
        course_c_type = ContentType.objects.get_for_model(Course)
        comments_qs = Comment.objects.filter(content_type=course_c_type, object_id=self.id)
        return comments_qs.count()


class Chapter(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField(null=True, blank=True)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.course.title} - {self.title}'

class Lesson(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField(null=True, blank=True)
    chapter = models.ForeignKey(Chapter, on_delete=models.CASCADE, blank=True, null=True)
    position = models.IntegerField(default=1)
    duration = models.CharField(max_length=10, blank=True, null=True)
    video       = models.FileField(upload_to=lesson_video_upload)
    thumbnail = models.ImageField(upload_to=lesson_video_upload)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.chapter.title} - {self.title}'

    @property
    def get_duration(self):
        return strftime("%H:%M:%S", gmtime(float(self.duration)))


class EnrolledCourse(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    courses = models.ManyToManyField(Course)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.instructor_set.first().username

class WishList(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    courses = models.ManyToManyField(Course)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.instructor_set.first().username


# Create Slug for Course
def post_save_create_course(sender, instance, created, *args, **kwargs):
    if created:
        if instance.slug is None and instance.title:
            instance.slug = slugify(instance.title)
        instance.save()

post_save.connect(post_save_create_course, sender=Course)

# Create Slug for Category
def post_save_create_category(sender, instance, created, *args, **kwargs):
    if created:
        if instance.slug is None and instance.name:
            instance.slug = slugify(instance.name)
        instance.save()

post_save.connect(post_save_create_category, sender=Category)

# Create Slug for Chapter
def post_save_create_chapter(sender, instance, created, *args, **kwargs):
    if created:
        if instance.slug is None and instance.title:
            instance.slug = slugify(instance.title)
        instance.save()

post_save.connect(post_save_create_chapter, sender=Chapter)

# Create Slug for Lesson
def post_save_create_lesson(sender, instance, created, *args, **kwargs):
    if created:
        clip = VideoFileClip(instance.video.path)
        instance.duration = clip.duration

        chapter = instance.chapter
        course = chapter.course
        course.duration += float(clip.duration)
        course.save()

        if instance.slug is None and instance.title:
            instance.slug = slugify(instance.title)
        instance.save()

post_save.connect(post_save_create_lesson, sender=Lesson)

events/models.py
from django.db import models
from django.contrib.contenttypes.fields import GenericRelation
from django.db.models.signals import post_save
from ckeditor_uploader.fields import RichTextUploadingField

from django.utils.text import slugify
from django.urls import reverse
from django.contrib.contenttypes.models import ContentType

from instructors.models import Instructor
from comments.models import Comment
from tags.models import Tag


def event_image_upload(instance, filename):
    return f'events/{instance.title}/{instance.title}_{filename}'


class Event(models.Model):
    title           = models.CharField(max_length=100)
    subtitle        = models.CharField(max_length=150)
    slug            = models.SlugField(blank=True, null=True)
    date            = models.DateField() 
    start_in        = models.TimeField()
    end_at          = models.TimeField()
    description     = models.TextField()
    content         = RichTextUploadingField(blank=True, null=True)
    address         = models.CharField(max_length=100)
    phone           = models.CharField(max_length=100)
    email           = models.CharField(max_length=100)
    site            = models.CharField(max_length=100)
    tags            = GenericRelation(Tag)
    comments        = GenericRelation(Comment)
    image           = models.ImageField(upload_to=event_image_upload)
    participants    = models.ManyToManyField(Instructor)
    created         = models.DateTimeField(auto_now=True)
    timestamp       = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title
    
    class Meta:
        ordering = ['-timestamp']

    def get_absolute_url(self):
        return reverse('events:detail', kwargs={'slug': self.slug})
    
    @property
    def comments_count(self):
        event_c_type = ContentType.objects.get_for_model(Event)
        comments_qs = Comment.objects.filter(content_type=event_c_type, object_id=self.id)
        return comments_qs.count()


# Create Slug for Event
def post_save_create_event_slug(sender, instance, created, *args, **kwargs):
    if created:
        if instance.slug is None and instance.title:
            instance.slug = slugify(instance.title)
        instance.save()

post_save.connect(post_save_create_event_slug, sender=Event)

events/views.py
from django.shortcuts import redirect, render
from django.views.generic import ListView, DetailView, UpdateView, CreateView, DeleteView
from django.db.models import Count
from django.contrib.contenttypes.models import ContentType
from .models import Event
from comments.models import Comment
from django.urls import reverse, reverse_lazy
from django.contrib import messages

class EventListView(ListView):
    model = Event
    context_object_name = 'events'
    template_name = 'events/events.html'
    paginate_by = 4

    
    def get_context_data(self, **kwargs):
        context = super(EventListView, self).get_context_data(**kwargs)
        context['latest'] = Event.objects.all().order_by('-timestamp')[:3]
        context['featured'] = Event.objects.all().order_by('-views')[:6]

        return context

class EventDetailView(DetailView):
    model = Event
    context_object_name = 'event'
    template_name = 'events/event-single.html'
    lookup_field = 'slug'

    
    def get_context_data(self, **kwargs):
        context = super(EventDetailView, self).get_context_data(**kwargs)
        context['latest'] = Event.objects.all().order_by('-timestamp')[:3]

        obj = self.get_object()

        comment_c_type = ContentType.objects.get_for_model(Event)
        comments_qs = Comment.objects.filter(content_type=comment_c_type, object_id=obj.id).order_by('-timestamp')
        context['comments'] = comments_qs

        return context

    def post(self, *args, **kwargs):
        body = self.request.POST.get('body')
        obj_id = self.request.POST.get('object_id') or None
        event_c_type = ContentType.objects.get_for_model(Event)
        qs = self.get_object()
        object_id = qs.id
        if obj_id is not None:
            comment_obj = Comment.objects.get(id=obj_id)
            if comment_obj:
                comment = Comment.objects.create(user=self.request.user, content_type=event_c_type, body=body, object_id=object_id, parent=comment_obj)
        else:
            comment = Comment.objects.create(user=self.request.user, content_type=event_c_type, body=body, object_id=object_id)
        if comment:
            comment.save()
            return redirect(reverse('events:detail', kwargs={'slug': qs.slug}))
    

class EventCreate(CreateView):
    model = Event
    fields = '__all__'
    exclude = ['slug','created', 'timestamp']
    template_name = 'events/event_form.html'

    def form_valid(self, form):
        form.save()
        return super(EventCreate, self).form_valid(form)

class EventUpdate(UpdateView):
    model = Event
    fields = '__all__'
    exclude = ['slug','created', 'timestamp']
    template_name = 'events/event_form.html'

class EventDelete(DeleteView):
    model = Event
    success_url = reverse_lazy('events:list')

    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)

events/templates/events/event-single.html
{% extends 'base.html' %}

{% block content %}
<!-- Inner Page Breadcrumb -->
<section class="inner_page_breadcrumb">
	<div class="container">
		<div class="row">
			<div class="col-xl-6 offset-xl-3 text-center">
				<div class="breadcrumb_content">
					<h4 class="breadcrumb_title">{{event.title}}</h4>
					<ol class="breadcrumb">
						<li class="breadcrumb-item"><a href="/">Home</a></li>
						<li class="breadcrumb-item active" aria-current="page">{{event.title}}</li>
					</ol>
				</div>
			</div>
		</div>
	</div>
</section>

<!-- Main Blog Post Content -->
<section class="blog_post_container">
	<div class="container">
		<div class="row">
			<div class="col-lg-8 col-xl-9">
				<div class="main_blog_post_content">
					<div class="mbp_thumb_post">
						<div class="details pt0">
							<h3 class="mb25">{{event.title}}</h3>
						</div>
						<div class="thumb">
							<img class="img-fluid" src="{{event.image.url}}" alt="12.jpg" style="width: 100%; height: 100%; max-height: 500px;">
							<div class="post_date">
								<h2>{{event.timestamp|date:'d'}}</h2> <span>{{event.timestamp|date:'M'}}</span>
							</div>
						</div>
						<div class="event_counter_plugin_container">
							<div class="event_counter_plugin_content" id="timer"
								data-timer="{{ event.date|date:'M d, Y' }} 00:00:00">
								<ul>
									<li>days<span id="days"></span></li>
									<li>Hours<span id="hours"></span></li>
									<li>Minutes<span id="minutes"></span></li>
									<li>Seconds<span id="seconds"></span></li>
								</ul>
							</div>
						</div>
						<div class="details">
							<h4>Event Description</h4>
							<p>{{event.description}} </p>
							<h4 class="mb0">Event Content</h4>
							<p>{{event.content|safe}}</p>
						</div>
						<ul class="blog_post_share mb0">
							<li>
								<p>Share</p>
							</li>
							<li><a href="#"><i class="fa fa-facebook"></i></a></li>
							<li><a href="#"><i class="fa fa-twitter"></i></a></li>
							<li><a href="#"><i class="fa fa-google"></i></a></li>
							<li><a href="#"><i class="fa fa-linkedin"></i></a></li>
							<li><a href="#"><i class="fa fa-dribbble"></i></a></li>
							<li><a href="#"><i class="fa fa-google"></i></a></li>
						</ul>
					</div>
					<div class="mbp_pagination_tab">
						<div class="row">
							<div class="col-lg-12">
								<h4 class="event_participator_tile">Event Participants</h4>
							</div>
							{% for instructor in event.participants.all %}
							<div class="col-sm-6 col-lg-6 col-xl-3">
								<div class="participator_team text-center">
									<div class="thumb">
										<img class="img-fluid" src="{{instructor.avatar.url}}"
											alt="{{instructor.username}}">
									</div>
									<div class="details">
										<h4>{{instructor.username}}</h4>
										<p>{{instructor.title}}</p>
									</div>
								</div>
							</div>
							{% endfor %}
						</div>
						<ul>
							<li class="list-inline-item float-left"></li>
							<li class="list-inline-item float-right"></li>
						</ul>
					</div>
					<div class="product_single_content style2 mb30">
						<h4 class="aii_title">Reviews</h4>
						<div class="mbp_pagination_comments">

							{% for comment in comments %}
							{% if comment.is_parent %}
							<div class="mbp_first media csv1">
								<img src="{{comment.user.instructor_set.first.avatar.url}}" class="mr-3"
									alt="review1.png">
								<div class="media-body">
									<h4 class="sub_title mt-0">{{comment.user.instructor_set.first.username}}
										<span class="sspd_review float-right">
											<ul>
												<li class="list-inline-item"><a href="#"><i class="fa fa-star"></i></a>
												</li>
												<li class="list-inline-item"><a href="#"><i class="fa fa-star"></i></a>
												</li>
												<li class="list-inline-item"><a href="#"><i class="fa fa-star"></i></a>
												</li>
												<li class="list-inline-item"><a href="#"><i class="fa fa-star"></i></a>
												</li>
												<li class="list-inline-item"><a href="#"><i class="fa fa-star"></i></a>
												</li>
												<li class="list-inline-item"></li>
											</ul>
										</span>
									</h4>
									<a class="sspd_postdate fz14" href="#">{{comment.timestamp|timesince}}</a>
									<p class="fz15 mt20">{{comment.body}}</p>
									<div class="ssp_reply float-right"><span
											class="flaticon-consulting-message"></span><span class="pl10">Reply</span>
									</div>

									{% for reply in comment.children %}
									<div class="sspd_review_liked">
										<a href="#"><i class="flaticon-like-1"></i>
											<span class="text-thm6 pl5 pr5 fz15">15</span>
											{{reply.body}}
										</a>
									</div>
									{% endfor %}
									{% if request.user.is_authenticated %}
									<form class="comments_form" method='POST' action='.'>
										{% csrf_token %}
										<input type="hidden" name="object_id" value="{{ comment.id }}">
										<div class="form-group">
											<label for="exampleFormControlTextarea1">Reply Content</label>
											<textarea class="form-control" name='body' id="exampleFormControlTextarea1"
												rows="6"></textarea>
										</div>
										<button type="submit" class="btn btn-thm">Reply <span
												class="flaticon-right-arrow-1"></span></button>
									</form>
									{% else %}
									<li class="list-inline-item pr15">
										<p>Sign in to Comment <a href="{% url 'auth:login' %}">Login</a> or <a
												href="{% url 'auth:signup' %}">Register</a></p>
									</li>
									{% endif %}
								</div>
							</div>
							<!-- <div class="custom_hr"></div> -->
							{% endif %}
							{% endfor %}
							<div class="text-center mt50">
								<div class="custom_hr"></div>
								<button type="button" class="more-review-btn btn">See more reviews</button>
							</div>
						</div>
					</div>
					<div class="product_single_content style2">
						<div class="mbp_comment_form style2">
							<h4>Add Reviews & Rate</h4>
							{% if request.user.is_authenticated %}
							<ul>
								<li class="list-inline-item pr15">
									<p>What is it like to Course?</p>
								</li>
								<li class="list-inline-item">
									<span class="sspd_review">
										<ul>
											<li class="list-inline-item"><a href="#"><i class="fa fa-star fz18"></i></a>
											</li>
											<li class="list-inline-item"><a href="#"><i class="fa fa-star fz18"></i></a>
											</li>
											<li class="list-inline-item"><a href="#"><i class="fa fa-star fz18"></i></a>
											</li>
											<li class="list-inline-item"><a href="#"><i class="fa fa-star fz18"></i></a>
											</li>
											<li class="list-inline-item"><a href="#"><i class="fa fa-star fz18"></i></a>
											</li>
											<li class="list-inline-item"></li>
										</ul>
									</span>
								</li>
							</ul>
							<form class="comments_form" method='POST' action='.'>
								{% csrf_token %}
								<div class="form-group">
									<label for="exampleFormControlTextarea1">Review Content</label>
									<textarea class="form-control" name='body' id="exampleFormControlTextarea1"
										rows="6"></textarea>
								</div>
								<button type="submit" class="btn btn-thm">Submit Review <span
										class="flaticon-right-arrow-1"></span></button>
							</form>
							{% else %}
							<li class="list-inline-item pr15">
								<p>Sign in to Comment <a href="{% url 'auth:login' %}">Login</a> or <a
										href="{% url 'auth:signup' %}">Register</a></p>
							</li>
							{% endif %}
						</div>
					</div>
				</div>
			</div>
			<div class="col-lg-4 col-xl-3 pl10 pr10">
				<div class="main_blog_post_widget_list">
					<div class="event_details_widget">
						<h4 class="title">Event Details</h4>
						<ul>
							<li><span class="flaticon-appointment"></span> Date: {{event.date}}</li>
							<li><span class="flaticon-clock"></span> Time: {{event.start_in|date:'P'}} -
								{{event.end_at|date:'P'}}</li>
							<li><span class="flaticon-placeholder"></span> Address: {{event.address}}</li>
						</ul>
					</div>
					<div class="event_details_widget">
						<h4 class="title">Event Details</h4>
						<ul>
							<li><span class="flaticon-phone-call"></span> {{event.phone}}</li>
							<li><span class="flaticon-email"></span> <a
									href="mailto:{{event.email}}">{{event.email}}</a></li>
							<li><span class="flaticon-www"></span> <a href="{{event.site}}">{{event.site}}</a></li>
						</ul>
					</div>
					<div class="blog_tag_widget">
						<h4 class="title">Tags</h4>
						<ul class="tag_list">
							<li class="list-inline-item"><a href="#">Photoshop</a></li>
							<li class="list-inline-item"><a href="#">Sketch</a></li>
							<li class="list-inline-item"><a href="#">Beginner</a></li>
							<li class="list-inline-item"><a href="#">UX/UI</a></li>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>
{% block extraScript %}
<script>
	$(document).ready(function () {
		const second = 1000,
			minute = second * 60,
			hour = minute * 60,
			day = hour * 24,
			timer = $('#timer').data('timer');
		// 'Dec 30, 2021 00:00:00'
		var countDown = new Date(timer).getTime(),
			x = setInterval(function () {
				let now = new Date().getTime(),
					distance = countDown - now;
					document.getElementById('days').innerText = Math.floor(distance / (day)),
					document.getElementById('hours').innerText = Math.floor((distance % (day)) / (hour)),
					document.getElementById('minutes').innerText = Math.floor((distance % (hour)) / (minute)),
					document.getElementById('seconds').innerText = Math.floor((distance % (minute)) / second);

					if(countDown <= now) {
						document.getElementById('days').innerText = '-',
						document.getElementById('hours').innerText = '-',
						document.getElementById('minutes').innerText = '-',
						document.getElementById('seconds').innerText = '-';
					}
			}, second);
	});
</script>
{% endblock %}
{% endblock %}

events/templates/events/event_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<!-- Inner Page Breadcrumb -->
<section class="inner_page_breadcrumb">
    <div class="container">
        <div class="row">
            <div class="col-xl-6 offset-xl-3 text-center">
                <div class="breadcrumb_content">
                    <h4 class="breadcrumb_title">Create a New Post</h4>
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="/">Home</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Create a New Post</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>
</section>

<!-- Our LogIn Register -->
<section class="our-log bgc-fa">
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <div class="login_form inner_page custom-form">
                    {{block.super}}
                    {{ form.non_field_errors }}
                    <form action="." method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="heading">
                            <h3 class="text-center">Create a New Post</h3>
                        </div>
                        {{form.media}}
                        {{ form|crispy }}
                        <!-- <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    {{form.title}}
                                    {{form.title.errors}}
                                </div>
                                <div class="form-group">
                                    {{form.price}}
                                    {{form.price.errors}}
                                </div>
                                <div class="form-group">
                                    {{form.discount}}
                                    {{form.discount.errors}}
                                </div>
                                <div class="form-group">
                                    {{form.duration.label_tag}} {{form.duration}}
                                    {{form.duration.label_tag}} {{form.duration.errors}}
                                </div>
                                <div class="form-group">
                                    {{form.full_lifetime_access.errors}}
                                    {{form.full_lifetime_access}} <label
                                        for="id_full_lifetime_access">{{form.full_lifetime_access.label}}</label>
                                </div>
                                <div class="form-group">
                                    {{form.assignments.errors}}
                                    {{form.assignments}} <label
                                        for="id_assignments">{{form.assignments.label_tag}}</label>
                                </div>
                                <div class="form-group">
                                    {{form.Certificate_of_completion.errors}}
                                    {{form.Certificate_of_completion}} <label
                                        for="id_Certificate_of_completion">{{form.Certificate_of_completion.label}}</label>
                                </div>
                                <div class="form-group">
                                    {{form.preview.label_tag}}
                                    {{form.preview}}
                                    {{form.preview.errors}}
                                </div>

                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    {{form.thumbnail.label_tag}}
                                    {{form.thumbnail}}
                                    {{form.thumbnail.errors}}
                                </div>
                                <div class="form-group">
                                    {{form.overview}}
                                    {{form.overview.errors}}
                                </div>
                                <div class="form-group">
                                    {{form.description}}
                                    {{form.description.errors}}
                                </div>
                                <div class="form-group">
                                    {{form.what_will_learn}}
                                    {{form.what_will_learn.errors}}
                                </div>
                                <div class="form-group">
                                    {{form.requirements}}
                                    {{form.requirements.errors}}
                                </div>
                                <div class="form-group">
                                    {{form.Skill_level}}
                                    {{form.Skill_level.errors}}
                                </div>
                                <div class="form-group">
                                    {{form.language}}
                                    {{form.language.errors}}
                                </div>
                                <div class="form-group">
                                    {{form.category}}
                                    {{form.category.errors}}
                                </div>
                            </div>
                        </div> -->

                        <button type="submit" class="btn btn-log btn-block btn-thm2">Submit</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock %}