blog/urls.py
from django.urls import path
from .views import PostListView, PostDetailView, PostCreate, PostUpdate, PostDelete

app_name = 'blog'

urlpatterns = [
    path('', PostListView.as_view(), name='list'),
    path('create/', PostCreate.as_view(), name='create'),
    path('<slug>/', PostDetailView.as_view(), name='detail'),
    path('<slug>/update/', PostUpdate.as_view(), name='update'),
    path('<slug>/delete/', PostDelete.as_view(), name='delete'),
]

cart/urls.py
from django.urls import path
from .views import add_to_cart, remove_from_cart, order, PaymentView

app_name = 'cart'

urlpatterns = [
    path('', order, name='order'),
    path('add-to-cart/<slug>/', add_to_cart, name='add_to_cart'),
    path('remove-from-cart/<slug>/', remove_from_cart, name='remove_from_cart'),
    path('payment/', PaymentView.as_view(), name='payment'),
]

courses/urls.py
from django.urls import path
from .views import (
    CoursesListView,
    CoursesDetailView,
    course_create,
    course_create_chapter,
    course_create_lesson,
    my_courses,
    category,
    add_to_wishlist,
    wish_list
)

app_name = 'courses'

urlpatterns = [
    path('', CoursesListView.as_view(), name='index'),
    path('categories/<slug>/', category, name='category'),
    path('create/', course_create, name='course_create'),
    path('my-courses/', my_courses, name='my_courses'),
    path('my-wishlist/', wish_list, name='wishlist'),
    path('create/<course_id>/create-chapter/', course_create_chapter, name='course_create_chapter'),
    path('create/<course_id>/create-lesson/', course_create_lesson, name='course_create_lesson'),
    path('<slug>/', CoursesDetailView.as_view(), name='detail'),
    path('add_to_wishlist/<slug>/', add_to_wishlist, name='add_to_wishlist'),
]

cart/models.py
from django.db import models
from django.conf import settings
from courses.models import Course


class OrderItem(models.Model):
    item = models.ForeignKey(Course, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)

    def __str__(self):
        return self.item.title


class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    items = models.ManyToManyField(OrderItem)
    start_date = models.DateTimeField(auto_now_add=True)
    ordered_date = models.DateTimeField()
    ordered = models.BooleanField(default=False)
    payment = models.ForeignKey(
        'Payment', on_delete=models.SET_NULL, blank=True, null=True)

    def __str__(self):
        return self.user.instructor_set.first().username

    @property
    def get_total(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.item.get_price
        return total


class Payment(models.Model):
    stripe_charge_id = models.CharField(max_length=50)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.SET_NULL, blank=True, null=True)
    amount = models.FloatField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username

cart/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib import messages
from django.views import View
from django.contrib.auth.decorators import login_required
from django.conf import settings
from .models import Order, OrderItem, Payment
from courses.models import Course, EnrolledCourse

from django.utils import timezone
from django.urls import reverse

import decimal
import stripe

stripe.api_key = settings.STRIPE_SECRET_KEY


def order(request):
    order_qs= Order.objects.filter(user=request.user, ordered=False)
    order = None
    if order_qs.exists():
        order = order_qs.first()
    
    context = {
        'order': order
    }

    return render(request, 'cart/cart.html', context)


@login_required
def add_to_cart(request, slug):
    course = get_object_or_404(Course, slug=slug)
    order_item, created = OrderItem.objects.get_or_create(user=request.user, item=course)

    if order_item:
        order_qs= Order.objects.filter(user=request.user, ordered=False)
        if order_qs.exists():
            order = order_qs.first()
        else:
            order = Order.objects.create(user=request.user, ordered=False, ordered_date=timezone.now())
        
        if order.items.filter(item__slug=order_item.item.slug).exists():
            messages.info(request, "This course is Exist in you Cart")
            return redirect(reverse('courses:detail', kwargs={'slug': slug}))
        else:
            order.items.add(order_item)
            order.ordered_date = timezone.now()
            order.save()

        messages.success(request, f'{order_item.item.title} successfully Added to the Cart.')
        return redirect(reverse('courses:detail', kwargs={'slug': slug}))


@login_required
def remove_from_cart(request, slug):
    item = get_object_or_404(Course, slug=slug)
    order_qs = Order.objects.filter(
        user=request.user,
        ordered=False
    )
    if order_qs.exists():
        order = order_qs[0]
        # check if the order item is in the order
        if order.items.filter(item__slug=item.slug).exists():
            order_item = OrderItem.objects.filter(
                item=item,
                user=request.user,
                ordered=False
            )[0]
            order.items.remove(order_item)
            messages.info(request, "This item was removed from your cart.")
            return redirect(reverse('cart:order'))
        else:
            messages.info(request, "This item was not in your cart")
            return redirect(reverse('cart:order'))
    else:
        messages.info(request, "You do not have an active order")
        return redirect(reverse('cart:order'))
    

class PaymentView(View):
    def get(self, *args, **kwargs):
        order = Order.objects.get(user=self.request.user, ordered=False)
        context = {
            'order': order,
            'pub_key': settings.STRIBE_PUB_KEY
        }
        return render(self.request, "cart/payment.html", context)

    def post(self, *args, **kwargs):
        order = Order.objects.get(user=self.request.user, ordered=False)
        token = self.request.POST.get('stripeToken')
        total = order.get_total
        amount = round(decimal.Decimal(total * 100))


        charge = stripe.Charge.create(
            amount=amount,  # cents
            currency="usd",
            source=token
        )

        # create the payment
        payment = Payment()
        payment.stripe_charge_id = charge['id']
        payment.user = self.request.user
        payment.amount = order.get_total
        payment.save()

        author_students = self.request.user.instructor_set.first()
        author_students.students += 1
        author_students.save()

        enrolled_qs = EnrolledCourse.objects.get(user=self.request.user)
        if enrolled_qs:
            enrolled = enrolled_qs
        else:
            enrolled = EnrolledCourse()
            enrolled.user = self.request.user
            enrolled.save()
        for course in order.items.all():
            enrolled.courses.add(course.item)
            enrolled.save()

        # assign the payment to the order
        order.ordered = True
        order.payment = payment
        order.save()

        for order_item in order.items.all():
            course = Course.objects.get(id=order_item.item.id)
            course.enrolled += 1
            course.save()

        messages.success(self.request, "Your order was successful!")
        return redirect("/")

        # except stripe.error.CardError as e:
        #     body = e.json_body
        #     err = body.get('error', {})
        #     messages.error(self.request, f"{err.get('message')}")
        #     return redirect("/")

        # except stripe.error.RateLimitError as e:
        #     # Too many requests made to the API too quickly
        #     messages.error(self.request, "Rate limit error")
        #     return redirect("/")

        # except stripe.error.InvalidRequestError as e:
        #     # Invalid parameters were supplied to Stripe's API
        #     messages.error(self.request, "Invalid parameters")
        #     return redirect("/")

        # except stripe.error.AuthenticationError as e:
        #     # Authentication with Stripe's API failed
        #     # (maybe you changed API keys recently)
        #     messages.error(self.request, "Not authenticated")
        #     return redirect("/")

        # except stripe.error.APIConnectionError as e:
        #     # Network communication with Stripe failed
        #     messages.error(self.request, "Network error")
        #     return redirect("/")

        # except stripe.error.StripeError as e:
        #     # Display a very generic error to the user, and maybe send
        #     # yourself an email
        #     messages.error(
        #         self.request, "Something went wrong. You were not charged. Please try again.")
        #     return redirect("/")

        # except Exception as e:
        #     # send an email to ourselves
        #     messages.error(
        #         self.request, "A serious error occurred. We have been notifed.")
        #     return redirect("/")

cart/templates/cart/cart.html
{% extends 'base.html' %}
{% load static %}


{% block content %}

<!-- Inner Page Breadcrumb -->
<section class="inner_page_breadcrumb">
	<div class="container">
		<div class="row">
			<div class="col-xl-6 offset-xl-3 text-center">
				<div class="breadcrumb_content">
					<h4 class="breadcrumb_title">Cart</h4>
					<ol class="breadcrumb">
						<li class="breadcrumb-item"><a href="/">Home</a></li>
						<li class="breadcrumb-item active" aria-current="page">Cart</li>
					</ol>
				</div>
			</div>
		</div>
	</div>
</section>

<!-- Shop Checkouts Content -->
<section class="shop-checkouts">
	<div class="container">
		<div class="row">
			<div class="col-md-12 col-lg-8 col-xl-8">
				<div class="cart_page_form">
					<form action="#">
						<table class="table table-responsive">
							<thead style="width: 100%;min-width: 100%;display: table;">
								<tr class="carttable_row">
									<th class="cartm_title">#</th>
									<th class="cartm_title">Course</th>
									<th class="cartm_title">Price</th>
									<th class="cartm_title">Overview</th>
								</tr>
							</thead>
							<tbody class="table_body">
								{% for order_item in order.items.all %}
								<tr>
									<td>{{forloop.counter}}</td>
									<th scope="row">
										<ul class="cart_list">
											<li class="list-inline-item pr15"><a
													href="{% url 'cart:remove_from_cart'  slug=order_item.item.slug %}"><img
														src="{% static 'images/shop/close.png' %}" alt="close.png"></a>
											</li>
											<li class="list-inline-item pr20"><a
													href="{% url 'courses:detail'  slug=order_item.item.slug %}"><img
														src="{{order_item.item.thumbnail.url}}"
														alt="{{order_item.item.title}}" width="120px" height="90px"></a>
											</li>
											<li class="list-inline-item"><a class="cart_title"
													href="{% url 'courses:detail'  slug=order_item.item.slug %}">{{order_item.item.title}}</a>
											</li>
										</ul>
									</th>
									<td>${{order_item.item.get_price}}</td>
									<td>{{order_item.item.overview|truncatechars:50}}</td>
								</tr>
								{% endfor %}
							</tbody>
						</table>
					</form>
				</div>
				<div class="checkout_form">
					<div class="checkout_coupon ui_kit_button">
						<form class="form-inline">
							<input class="form-control" type="search" placeholder="Coupon Code" aria-label="Search">
							<button type="button" class="btn btn2">Apply Coupon</button>
							<button type="button" class="btn btn3">Update Cart</button>
						</form>
					</div>
				</div>
			</div>
			<div class="col-lg-4 col-xl-4">
				<div class="order_sidebar_widget mb30">
					<h4 class="title">Cart Totals</h4>
					<ul>
						<li class="subtitle">
							<p>Total <span class="float-right totals color-orose">${{order.get_total}}</span></p>
						</li>
					</ul>
				</div>
				<div class="ui_kit_button payment_widget_btn">
					<a href="{% url 'cart:payment' %}" type="button"
						class="btn dbxshad btn-lg btn-thm3 circle btn-block">Proceed To
						Checkout</a>
				</div>
			</div>
		</div>
	</div>
</section>

{% endblock %}

cart/templates/cart/payment.html
{% extends "base.html" %}

{% block extra_head %}
<style>
  #stripeBtnLabel {
    font-family: "Helvetica Neue", Helvetica, sans-serif;
    font-size: 16px;
    font-variant: normal;
    padding: 0;
    margin: 0;
    -webkit-font-smoothing: antialiased;
    font-weight: 500;
    display: block;
  }

  #stripeBtn {
    border: none;
    border-radius: 4px;
    outline: none;
    text-decoration: none;
    color: #fff;
    background: #32325d;
    white-space: nowrap;
    display: inline-block;
    height: 40px;
    line-height: 40px;
    padding: 0 14px;
    box-shadow: 0 4px 6px rgba(50, 50, 93, .11), 0 1px 3px rgba(0, 0, 0, .08);
    border-radius: 4px;
    font-size: 15px;
    font-weight: 600;
    letter-spacing: 0.025em;
    text-decoration: none;
    -webkit-transition: all 150ms ease;
    transition: all 150ms ease;
    float: left;
    margin-left: 12px;
    margin-top: 28px;
  }

  button:hover {
    transform: translateY(-1px);
    box-shadow: 0 7px 14px rgba(50, 50, 93, .10), 0 3px 6px rgba(0, 0, 0, .08);
    background-color: #43458b;
  }

  #stripe-form {
    padding: 30px;
    height: 120px;
  }

  #card-errors {
    height: 20px;
    padding: 4px 0;
    color: #fa755a;
  }

  .stripe-form-row {
    width: 70%;
    float: left;
  }

  /**
 * The CSS shown here will not be introduced in the Quickstart guide, but shows
 * how you can use CSS to style your Element's container.
 */
  .StripeElement {
    box-sizing: border-box;
    height: 40px;
    padding: 10px 12px;
    border: 1px solid transparent;
    border-radius: 4px;
    background-color: white;
    box-shadow: 0 1px 3px 0 #e6ebf1;
    -webkit-transition: box-shadow 150ms ease;
    transition: box-shadow 150ms ease;
  }

  .StripeElement--focus {
    box-shadow: 0 1px 3px 0 #cfd7df;
  }

  .StripeElement--invalid {
    border-color: #fa755a;
  }

  .StripeElement--webkit-autofill {
    background-color: #fefde5 !important;
  }
</style>
{% endblock extra_head %}

{% block content %}

<!-- Inner Page Breadcrumb -->
<section class="inner_page_breadcrumb">
  <div class="container">
    <div class="row">
      <div class="col-xl-6 offset-xl-3 text-center">
        <div class="breadcrumb_content">
          <h4 class="breadcrumb_title">Payment</h4>
          <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="/">Home</a></li>
            <li class="breadcrumb-item active" aria-current="page">Payment</li>
          </ol>
        </div>
      </div>
    </div>
  </div>
</section>

<main>
  <div class="container wow fadeIn">

    <h2 class="my-5 h2 text-center">Payment</h2>

    <div class="row">

      <div class="col-md-12 mb-4">
        <div class="card">

          <script src="https://js.stripe.com/v3/"></script>

          <form action="." method="post" id="stripe-form">
            {% csrf_token %}
            <div class="stripe-form-row">
              <label for="card-element" id="stripeBtnLabel">
                Credit or debit card
              </label>
              <div id="card-element" class="StripeElement StripeElement--empty">
                <div class="__PrivateStripeElement"
                  style="margin: 0px !important; padding: 0px !important; border: none !important; display: block !important; background: transparent !important; position: relative !important; opacity: 1 !important;">
                  <iframe frameborder="0" allowtransparency="true" scrolling="no" name="__privateStripeFrame5"
                    allowpaymentrequest="true"
                    src="https://js.stripe.com/v3/elements-inner-card-19066928f2ed1ba3ffada645e45f5b50.html#style[base][color]=%2332325d&amp;style[base][fontFamily]=%22Helvetica+Neue%22%2C+Helvetica%2C+sans-serif&amp;style[base][fontSmoothing]=antialiased&amp;style[base][fontSize]=16px&amp;style[base][::placeholder][color]=%23aab7c4&amp;style[invalid][color]=%23fa755a&amp;style[invalid][iconColor]=%23fa755a&amp;componentName=card&amp;wait=false&amp;rtl=false&amp;keyMode=test&amp;origin=https%3A%2F%2Fstripe.com&amp;referrer=https%3A%2F%2Fstripe.com%2Fdocs%2Fstripe-js&amp;controllerId=__privateStripeController1"
                    title="Secure payment input frame"
                    style="border: none !important; margin: 0px !important; padding: 0px !important; width: 1px !important; min-width: 100% !important; overflow: hidden !important; display: block !important; height: 19.2px;"></iframe><input
                    class="__PrivateStripeElement-input" aria-hidden="true" aria-label=" " autocomplete="false"
                    maxlength="1"
                    style="border: none !important; display: block !important; position: absolute !important; height: 1px !important; top: 0px !important; left: 0px !important; padding: 0px !important; margin: 0px !important; width: 100% !important; opacity: 0 !important; background: transparent !important; pointer-events: none !important; font-size: 16px !important;">
                </div>
              </div>

              <!-- Used to display form errors. -->
              <div id="card-errors" role="alert"></div>
            </div>

            <button id="stripeBtn">Submit Payment</button>
          </form>

        </div>
      </div>

      <!--Grid column-->
      <div class="col-md-12 mb-4">

        <!-- Heading -->
        <h4 class="d-flex justify-content-between align-items-center mb-3">
          <span class="text-muted">Your cart</span>
          <span class="badge badge-secondary badge-pill">{{ order.items.count }}</span>
        </h4>

        <!-- Cart -->
        <ul class="list-group mb-3 z-depth-1">
          {% for order_item in order.items.all %}
          <li class="list-group-item d-flex justify-content-between lh-condensed">
            <div>
              <h6 class="my-0">{{ order_item.item.title}}</h6>
              <small class="text-muted">{{ order_item.item.overview}}</small>
            </div>
            <span class="text-muted">${{ order_item.item.get_price }}</span>
          </li>
          {% endfor %}
          <li class="list-group-item d-flex justify-content-between">
            <span>Total (USD)</span>
            <strong>${{ order.get_total }}</strong>
          </li>
        </ul>
        <!-- Cart -->

      </div>
      <!--Grid column-->

    </div>

  </div>
</main>


<script nonce="">  // Create a Stripe client.
  var stripe = Stripe('pk_test_MDwzuN5BjaLGQQWfjizGcZDT00EfRGMhjm');
  // Create an instance of Elements.
  var elements = stripe.elements();
  // Custom styling can be passed to options when creating an Element.
  // (Note that this demo uses a wider set of styles than the guide below.)
  var style = {
    base: {
      color: '#32325d',
      fontFamily: '"Helvetica Neue", Helvetica, sans-serif',
      fontSmoothing: 'antialiased',
      fontSize: '16px',
      '::placeholder': {
        color: '#aab7c4'
      }
    },
    invalid: {
      color: '#fa755a',
      iconColor: '#fa755a'
    }
  };
  // Create an instance of the card Element.
  var card = elements.create('card', { style: style });
  // Add an instance of the card Element into the `card-element` <div>.
  card.mount('#card-element');
  // Handle real-time validation errors from the card Element.
  card.addEventListener('change', function (event) {
    var displayError = document.getElementById('card-errors');
    if (event.error) {
      displayError.textContent = event.error.message;
    } else {
      displayError.textContent = '';
    }
  });
  // Handle form submission.
  var form = document.getElementById('stripe-form');
  form.addEventListener('submit', function (event) {
    event.preventDefault();
    stripe.createToken(card).then(function (result) {
      if (result.error) {
        // Inform the user if there was an error.
        var errorElement = document.getElementById('card-errors');
        errorElement.textContent = result.error.message;
      } else {
        // Send the token to your server.
        stripeTokenHandler(result.token);
      }
    });
  });
  // Submit the form with the token ID.
  function stripeTokenHandler(token) {
    // Insert the token ID into the form so it gets submitted to the server
    var form = document.getElementById('stripe-form');
    var hiddenInput = document.createElement('input');
    hiddenInput.setAttribute('type', 'hidden');
    hiddenInput.setAttribute('name', 'stripeToken');
    hiddenInput.setAttribute('value', token.id);
    form.appendChild(hiddenInput);
    // Submit the form
    form.submit();
  }
</script>

{% endblock content %}