blog/urls.py
from django.urls import path
from .views import PostListView, PostDetailView, PostCreate, PostUpdate, PostDelete

app_name = 'blog'

urlpatterns = [
    path('', PostListView.as_view(), name='list'),
    path('create/', PostCreate.as_view(), name='create'),
    path('<slug>/', PostDetailView.as_view(), name='detail'),
    path('<slug>/update/', PostUpdate.as_view(), name='update'),
    path('<slug>/delete/', PostDelete.as_view(), name='delete'),
]

instructors/urls.py
from django.urls import path
from .views import login_view, logout_view, signup, become_instructor

app_name='auth'

urlpatterns = [
    path('login/', login_view, name='login'),
    path('signup/', signup, name='signup'),
    path('logout/', logout_view, name='logout'),
    
    path('become-instructor/', become_instructor, name='become_instructor'),
]

blog/models.py
from django.db import models
from django.contrib.contenttypes.fields import GenericRelation
from django.db.models.signals import post_save
from ckeditor_uploader.fields import RichTextUploadingField

from django.utils.text import slugify
from django.urls import reverse
from django.contrib.contenttypes.models import ContentType

from instructors.models import Instructor
from comments.models import Comment
from tags.models import Tag


def blog_image_upload(instance, filename):
    return f'blog/{instance.title}/{instance.title}_{filename}'


class Category(models.Model):
    name = models.CharField(max_length=50)
    slug = models.SlugField(blank=True, null=True)

    class Meta:
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name


class Post(models.Model):
    title           = models.CharField(max_length=100)
    slug            = models.SlugField(blank=True, null=True)
    description     = models.TextField()
    content         = RichTextUploadingField(blank=True, null=True)
    tags            = GenericRelation(Tag)
    comments        = GenericRelation(Comment)
    author          = models.ForeignKey(Instructor, on_delete=models.CASCADE)
    image           = models.ImageField(upload_to=blog_image_upload)
    category        =  models.ManyToManyField(Category)
    views           = models.PositiveIntegerField(default=0)
    created         = models.DateTimeField(auto_now=True)
    timestamp       = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-timestamp']

    def get_absolute_url(self):
        return reverse('blog:detail', kwargs={'slug': self.slug})
    
    @property
    def comments_count(self):
        course_c_type = ContentType.objects.get_for_model(Post)
        comments_qs = Comment.objects.filter(content_type=course_c_type, object_id=self.id)
        return comments_qs.count()

# Create Slug for Category
def post_save_create_category_slug(sender, instance, created, *args, **kwargs):
    if created:
        if instance.slug is None and instance.name:
            instance.slug = slugify(instance.name)
        instance.save()

post_save.connect(post_save_create_category_slug, sender=Category)

# Create Slug for Post
def post_save_create_post_slug(sender, instance, created, *args, **kwargs):
    if created:
        if instance.slug is None and instance.title:
            instance.slug = slugify(instance.title)
        instance.save()

post_save.connect(post_save_create_post_slug, sender=Post)

blog/views.py
from django.shortcuts import redirect, render
from django.views.generic import ListView, DetailView, UpdateView, CreateView, DeleteView
from django.db.models import Count
from django.contrib.contenttypes.models import ContentType
from .models import Post, Category
from comments.models import Comment
from django.urls import reverse, reverse_lazy
from django.contrib import messages
from tags.models import Tag

class PostListView(ListView):
    model = Post
    context_object_name = 'posts'
    template_name = 'blog/blog.html'
    paginate_by = 4

    
    def get_context_data(self, **kwargs):
        context = super(PostListView, self).get_context_data(**kwargs)
        context['latest'] = Post.objects.all().order_by('-timestamp')[:3]
        context['featured'] = Post.objects.all().order_by('-views')[:6]

        context['top_categories'] = Category.objects.annotate(q_count=Count('post')).order_by('-q_count')[:4]

        return context

class PostDetailView(DetailView):
    model = Post
    context_object_name = 'post'
    template_name = 'blog/blog-single.html'
    lookup_field = 'slug'

    
    def get_context_data(self, **kwargs):
        context = super(PostDetailView, self).get_context_data(**kwargs)
        context['latest'] = Post.objects.all().order_by('-timestamp')[:3]
        context['top_categories'] = Category.objects.annotate(q_count=Count('post')).order_by('-q_count')[:4]

        obj = self.get_object()
        obj.views += 1
        obj.save()

        comment_c_type = ContentType.objects.get_for_model(Post)
        comments_qs = Comment.objects.filter(content_type=comment_c_type, object_id=obj.id).order_by('-timestamp')
        context['comments'] = comments_qs

        tags_qs = Tag.objects.filter(content_type=comment_c_type, object_id=obj.id)
        context['tags'] = tags_qs

        return context

    def post(self, *args, **kwargs):
        body = self.request.POST.get('body')
        obj_id = self.request.POST.get('object_id') or None
        post_c_type = ContentType.objects.get_for_model(Post)
        qs = self.get_object()
        object_id = qs.id
        if obj_id is not None:
            comment_obj = Comment.objects.get(id=obj_id)
            if comment_obj:
                comment = Comment.objects.create(user=self.request.user, content_type=post_c_type, body=body, object_id=object_id, parent=comment_obj)
        else:
            comment = Comment.objects.create(user=self.request.user, content_type=post_c_type, body=body, object_id=object_id)
        if comment:
            comment.save()
            return redirect(reverse('blog:detail', kwargs={'slug': qs.slug}))
    

class PostCreate(CreateView):
    model = Post
    fields = ['title', 'description', 'content', 'image', 'category']
    template_name = 'blog/post_form.html'

    def form_valid(self, form):
        tags = self.request.POST.get('tags').split(', ')
        post_c_type = ContentType.objects.get_for_model(Post)
        form.instance.author = self.request.user.instructor_set.first()
        # self.user.teams.add(form.instance)
        form.save()
        
        for tag in tags:
            qs = Tag.objects.create(content_type=post_c_type, name=tag, object_id=form.instance.id)
            qs.save()
        return super(PostCreate, self).form_valid(form)

class PostUpdate(UpdateView):
    model = Post
    fields = ['title', 'description', 'content', 'image', 'category']
    template_name = 'blog/post_form.html'

class PostDelete(DeleteView):
    model = Post
    success_url = reverse_lazy('blog:list')

    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)

blog/templates/blog/blog-single.html
{% extends 'base.html' %}

{% block content %}

<!-- Inner Page Breadcrumb -->
<section class="inner_page_breadcrumb">
	<div class="container">
		<div class="row">
			<div class="col-xl-6 offset-xl-3 text-center">
				<div class="breadcrumb_content">
					<h4 class="breadcrumb_title">Blog</h4>
					<ol class="breadcrumb">
						<li class="breadcrumb-item"><a href="/">Home</a></li>
						<li class="breadcrumb-item active" aria-current="page">Blog</li>
					</ol>
				</div>
			</div>
		</div>
	</div>
</section>

<!-- Main Blog Post Content -->
<section class="blog_post_container">
	<div class="container">
		<div class="row">
			<div class="col-lg-8 col-xl-9">
				<div class="main_blog_post_content">
					<div class="mbp_thumb_post">
						<div class="thumb">
							<img class="img-fluid" src="{{post.image.url}}" alt="{{post.title}}"
								style="width: 100%; height: 100%; max-height: 500px;">
							<div class="tag">{% for cat in post.category.all %} {{cat.name}} {% endfor %}</div>
							<div class="post_date">
								<h2>{{post.timestamp|date:'d'}}</h2> <span>{{post.timestamp|date:'M'}}</span>
							</div>
						</div>
						<div class="details" style='overflow:hidden;'>
							<h3>{{post.title}}</h3>
							<ul class="post_meta">
								<li><a href="#"><span class="flaticon-profile"></span></a></li>
								<li><a href="#"><span>{{post.author}}</span></a></li>
								<li><a href="#"><span class="flaticon-comment"></span></a></li>
								<li><a href="#"><span>{{post.comments_count}} comments</span></a></li>
							</ul>
							<h4>Description</h4>
							<p class="mb25">{{post.description}}</p>
							<h4 class="mb0">Content</h4>
							<p class="mb25" style='max-width: 100%;'>{{post.content|safe}}</p>
						</div>
						<ul class="blog_post_share">
							<li>
								<p>Share</p>
							</li>
							<li><a href="#"><i class="fa fa-facebook"></i></a></li>
							<li><a href="#"><i class="fa fa-twitter"></i></a></li>
							<li><a href="#"><i class="fa fa-google"></i></a></li>
							<li><a href="#"><i class="fa fa-linkedin"></i></a></li>
							<li><a href="#"><i class="fa fa-dribbble"></i></a></li>
							<li><a href="#"><i class="fa fa-google"></i></a></li>
						</ul>
					</div>
					<div class="mbp_pagination_tab">
						<div class="row">
							{% if post.get_next_by_created_at %}
							<div class="col-sm-6 col-lg-6">
								<div class="pag_prev">
									<a href="{% url 'blog:detail' slug=post.get_next_by_created_at.slug %}"><span
											class="flaticon-left-arrow"></span>Previous Post</a> <br>
									<p>{{post.get_next_by_created_at.title}}</p>
								</div>
							</div>
							{% endif %}
							{% if post.get_previous_by_created_at %}
							<div class="col-sm-6 col-lg-6">
								<div class="pag_next text-right">
									<a href="{% url 'blog:detail' slug=post.get_previous_by_created_at.slug %}">Next
										Post <span class="flaticon-right-arrow-1"></span></a> <br>
									<p>{{post.get_previous_by_created_at.title}}</p>
								</div>
							</div>
							{% endif %}
						</div>
						<ul>
							<li class="list-inline-item float-left"></li>
							<li class="list-inline-item float-right"></li>
						</ul>
					</div>
					<div class="product_single_content style2 mb30">
						<h4 class="aii_title">Reviews</h4>
						<div class="mbp_pagination_comments">

							{% for comment in comments %}
							{% if comment.is_parent %}
							<div class="mbp_first media csv1">
								<img src="{{comment.user.instructor_set.first.avatar.url}}" class="mr-3"
									alt="review1.png">
								<div class="media-body">
									<h4 class="sub_title mt-0">{{comment.user.instructor_set.first.username}}
										<span class="sspd_review float-right">
											<ul>
												<li class="list-inline-item"><a href="#"><i class="fa fa-star"></i></a>
												</li>
												<li class="list-inline-item"><a href="#"><i class="fa fa-star"></i></a>
												</li>
												<li class="list-inline-item"><a href="#"><i class="fa fa-star"></i></a>
												</li>
												<li class="list-inline-item"><a href="#"><i class="fa fa-star"></i></a>
												</li>
												<li class="list-inline-item"><a href="#"><i class="fa fa-star"></i></a>
												</li>
												<li class="list-inline-item"></li>
											</ul>
										</span>
									</h4>
									<a class="sspd_postdate fz14" href="#">{{comment.timestamp|timesince}}</a>
									<p class="fz15 mt20">{{comment.body}}</p>
									<div class="ssp_reply float-right"><span
											class="flaticon-consulting-message"></span><span class="pl10">Reply</span>
									</div>

									{% for reply in comment.children %}
									<div class="sspd_review_liked">
										<a href="#"><i class="flaticon-like-1"></i>
											<span class="text-thm6 pl5 pr5 fz15">15</span>
											{{reply.body}}
										</a>
									</div>
									{% endfor %}
									{% if request.user.is_authenticated %}
									<form class="comments_form" method='POST' action='.'>
										{% csrf_token %}
										<input type="hidden" name="object_id" value="{{ comment.id }}">
										<div class="form-group">
											<label for="exampleFormControlTextarea1">Reply Content</label>
											<textarea class="form-control" name='body' id="exampleFormControlTextarea1"
												rows="6"></textarea>
										</div>
										<button type="submit" class="btn btn-thm">Reply <span
												class="flaticon-right-arrow-1"></span></button>
									</form>
									{% else %}
									<li class="list-inline-item pr15">
										<p>Sign in to Comment <a href="{% url 'auth:login' %}">Login</a> or <a
												href="{% url 'auth:signup' %}">Register</a></p>
									</li>
									{% endif %}
								</div>
							</div>
							<!-- <div class="custom_hr"></div> -->
							{% endif %}
							{% endfor %}
							<div class="text-center mt50">
								<div class="custom_hr"></div>
								<button type="button" class="more-review-btn btn">See more reviews</button>
							</div>
						</div>
					</div>
					<div class="product_single_content style2">
						<div class="mbp_comment_form style2">
							<h4>Add Reviews & Rate</h4>
							{% if request.user.is_authenticated %}
							<ul>
								<li class="list-inline-item pr15">
									<p>What is it like to Course?</p>
								</li>
								<li class="list-inline-item">
									<span class="sspd_review">
										<ul>
											<li class="list-inline-item"><a href="#"><i class="fa fa-star fz18"></i></a>
											</li>
											<li class="list-inline-item"><a href="#"><i class="fa fa-star fz18"></i></a>
											</li>
											<li class="list-inline-item"><a href="#"><i class="fa fa-star fz18"></i></a>
											</li>
											<li class="list-inline-item"><a href="#"><i class="fa fa-star fz18"></i></a>
											</li>
											<li class="list-inline-item"><a href="#"><i class="fa fa-star fz18"></i></a>
											</li>
											<li class="list-inline-item"></li>
										</ul>
									</span>
								</li>
							</ul>
							<form class="comments_form" method='POST' action='.'>
								{% csrf_token %}
								<div class="form-group">
									<label for="exampleFormControlTextarea1">Review Content</label>
									<textarea class="form-control" name='body' id="exampleFormControlTextarea1"
										rows="6"></textarea>
								</div>
								<button type="submit" class="btn btn-thm">Submit Review <span
										class="flaticon-right-arrow-1"></span></button>
							</form>
							{% else %}
							<li class="list-inline-item pr15">
								<p>Sign in to Comment <a href="{% url 'auth:login' %}">Login</a> or <a
										href="{% url 'auth:signup' %}">Register</a></p>
							</li>
							{% endif %}
						</div>
					</div>
				</div>
			</div>
			<div class="col-lg-4 col-xl-3 pl10 pr10">
				<div class="main_blog_post_widget_list">
					<div class="blog_search_widget">
						<div class="input-group mb-3">
							<input type="text" class="form-control" placeholder="Search Here"
								aria-label="Recipient's username" aria-describedby="button-addon2">
							<div class="input-group-append">
								<button class="btn btn-outline-secondary" type="button" id="button-addon2"><span
										class="flaticon-magnifying-glass"></span></button>
							</div>
						</div>
					</div>
					<div class="blog_category_widget">
						<ul class="list-group">
							<h4 class="title">Category</h4>
							{% for category in top_categories %}
							<li class="list-group-item d-flex justify-content-between align-items-center">
								{{category.name|title}} <span class="float-right">{{category.post_set.count}}</span>
							</li>
							{% endfor %}
						</ul>
					</div>
					<div class="blog_recent_post_widget media_widget">
						<h4 class="title">Recent Posts</h4>
						{% for post in latest %}
						<div class="media">
							<a href="{{post.get_absolute_url}}"><img class="align-self-start mr-3"
									src="{{post.image.url}}" alt="{{post.title}}">
								<div class="media-body">
									<h5 class="mt-0 post_title">{{post.title}}</h5>
									<a href="#">{{post.timestamp|timesince}}.</a>
								</div>
							</a>
						</div>
						{% endfor %}
					</div>
					<div class="blog_tag_widget">
						<h4 class="title">Tags</h4>
						<ul class="tag_list">
							{% for tag in tags %}
							<li class="list-inline-item"><a href="#">{{tag.name}}</a></li>
							{% endfor %}
						</ul>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>
{% endblock %}

blog/templates/blog/blog.html
{% extends 'base.html' %}

{% block title %} {{ block.super }} | Blog {% endblock %}

{% block content %}

<!-- Inner Page Breadcrumb -->
<section class="inner_page_breadcrumb">
	<div class="container">
		<div class="row">
			<div class="col-xl-6 offset-xl-3 text-center">
				<div class="breadcrumb_content">
					<h4 class="breadcrumb_title">Blog</h4>
					<ol class="breadcrumb">
						<li class="breadcrumb-item"><a href="/">Home</a></li>
						<li class="breadcrumb-item active" aria-current="page">Blog</li>
					</ol>
				</div>
			</div>
		</div>
	</div>
</section>

<!-- Main Blog Post Content -->
<section class="blog_post_container bgc-fa">
	<div class="container">
		<div class="row">
			<div class="col-lg-6 offset-lg-3">
				<div class="main-title text-center">
					<h3 class="mt0 mb0">Featured Posts</h3>
				</div>
			</div>
		</div>
		<div class="row">
			<div class="col-lg-12">
				<div class="feature_post_slider">
					{% for post in featured %}
					<div class="item">
						<div class="blog_post">
							<div class="thumb">
								<a href="{{post.get_absolute_url}}"><img class="img-fluid w100" src="{{post.image.url}}"
										alt="{{post.title}}" style="height: 280px;"></a>
								<a class="post_date" href="#">{{post.timestamp|timesince}}</a>
							</div>
							<div class="details">
								<h5>{% for cat in post.category.all %} {{cat.name}} {% endfor %}</h5>
								<a href="{{post.get_absolute_url}}">
									<h4>{{post.title}}</h4>
								</a>
							</div>
						</div>
					</div>
					{% endfor %}
				</div>
			</div>
		</div>
	</div>
</section>

<!-- Main Blog Post Content -->
<section class="blog_post_container">
	<div class="container">
		<div class="row">
			<div class="col-lg-8 col-xl-9">
				<div class="main_blog_post_content">
					{% for post in posts %}
					<div class="mbp_thumb_post">
						<div class="thumb">
							<a href="{{post.get_absolute_url}}"><img class="img-fluid" src="{{post.image.url}}"
									alt="{{post.title}}" style='width: 100%; max-height: 500px;'></a>
							<div class="tag">{% for cat in post.category.all %} {{cat.name}} {% endfor %}</div>
							<div class="post_date">
								<h2>{{post.timestamp|date:'d'}}</h2> <span>{{post.timestamp|date:'M'}}</span>
							</div>
						</div>
						<div class="details">
							<a href="{{post.get_absolute_url}}">
								<h3>{{post.title}}</h3>
							</a>
							<ul class="post_meta">
								<li><a href="#"><span class="flaticon-profile"></span></a></li>
								<li><a href="#"><span>{{post.author}}</span></a></li>
								<li><a href="#"><span class="flaticon-comment"></span></a></li>
								<li><a href="#"><span>{{post.comments_count}} comments</span></a></li>
							</ul>
							<p>{{post.description|truncatechars:250}}</p>
						</div>
					</div>
					{% endfor %}
					<div class="row">
						<div class="col-lg-12">
							{% if paginator %}
							<div class="mbp_pagination">
								<ul class="page_navigation">
									{% if page_obj.has_previous %}
									<li class="page-item">
										<a class="page-link" href="?page={{ page_obj.previous_page_number }}"
											tabindex="-1" aria-disabled="true"> <span
												class="flaticon-left-arrow"></span> Prev</a>
									</li>
									{% endif %}
									<li class="page-item active" aria-current="page">
										<a class="page-link" href="?page={{ page_obj.number }}"
											style="color: #fff;">{{ page_obj.number }} <span
												class="sr-only">(current)</span></a>
									</li>
									{% if page_obj.has_next %}
									<li class="page-item">
										<a class="page-link" href="?page={{ page_obj.next_page_number }}">Next <span
												class="flaticon-right-arrow-1"></span></a>
									</li>
									{% endif %}
								</ul>
							</div>
							{% endif %}
						</div>
					</div>
				</div>
			</div>
			<div class="col-lg-4 col-xl-3 pl10 pr10">
				<div class="blog_search_widget">
					<form action="{% url 'search' %}" method="get">
						<div class="main_blog_post_widget_list">
							<div class="input-group mb-3">
								<input type="text" name="search_post" class="form-control" placeholder="Search Here"
									aria-label="Recipient's username" aria-describedby="button-addon2">
								<div class="input-group-append">
									<button class="btn btn-outline-secondary" type="submit" id="button-addon2"><span
											class="flaticon-magnifying-glass"></span></button>
								</div>
							</div>
						</div>
					</form>
				</div>
				<div class="blog_category_widget">
					<ul class="list-group">
						<h4 class="title">Category</h4>
						{% for category in top_categories %}
						<li class="list-group-item d-flex justify-content-between align-items-center">
							{{category.name|title}} <span class="float-right">{{category.post_set.count}}</span>
						</li>
						{% endfor %}
					</ul>
				</div>
				<div class="blog_recent_post_widget media_widget">
					<h4 class="title">Recent Posts</h4>
					{% for post in latest %}
					<div class="media">
						<a href="{{post.get_absolute_url}}"><img class="align-self-start mr-3" src="{{post.image.url}}"
								alt="{{post.title}}">
							<div class="media-body">
								<h5 class="mt-0 post_title">{{post.title}}</h5>
								<a href="#">{{post.timestamp|timesince}}.</a>
							</div>
						</a>
					</div>
					{% endfor %}
				</div>
				<div class="blog_tag_widget">
					<h4 class="title">Tags</h4>
					<ul class="tag_list">
						<li class="list-inline-item"><a href="#">Photoshop</a></li>
						<li class="list-inline-item"><a href="#">Sketch</a></li>
						<li class="list-inline-item"><a href="#">Beginner</a></li>
						<li class="list-inline-item"><a href="#">UX/UI</a></li>
					</ul>
				</div>
			</div>
		</div>
	</div>
	</div>
</section>
{% endblock %}

blog/templates/blog/post_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<!-- Inner Page Breadcrumb -->
<section class="inner_page_breadcrumb">
    <div class="container">
        <div class="row">
            <div class="col-xl-6 offset-xl-3 text-center">
                <div class="breadcrumb_content">
                    <h4 class="breadcrumb_title">Create a New Post</h4>
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="/">Home</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Create a New Post</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>
</section>

<!-- Our LogIn Register -->
<section class="our-log bgc-fa">
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <div class="login_form inner_page custom-form">
                    {{block.super}}
                    {{ form.non_field_errors }}
                    <form action="." method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="heading">
                            <h3 class="text-center">Create a New Post</h3>
                        </div>
                        {{form.media}}
                        {{ form|crispy }}
                        <div class="form-group">
                            <label for="tags">Tags</label>
                            <input type="text" name="tags" id="tags" class="form-control">
                        </div>


                        <button type="submit" class="btn btn-log btn-block btn-thm2">Submit</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock %}