blog/urls.py
from django.urls import path
from .views import PostListView, PostDetailView, PostCreate, PostUpdate, PostDelete

app_name = 'blog'

urlpatterns = [
    path('', PostListView.as_view(), name='list'),
    path('create/', PostCreate.as_view(), name='create'),
    path('<slug>/', PostDetailView.as_view(), name='detail'),
    path('<slug>/update/', PostUpdate.as_view(), name='update'),
    path('<slug>/delete/', PostDelete.as_view(), name='delete'),
]

courses/urls.py
from django.urls import path
from .views import (
    CoursesListView,
    CoursesDetailView,
    course_create,
    course_create_chapter,
    course_create_lesson,
    my_courses,
    category,
    add_to_wishlist,
    wish_list
)

app_name = 'courses'

urlpatterns = [
    path('', CoursesListView.as_view(), name='index'),
    path('categories/<slug>/', category, name='category'),
    path('create/', course_create, name='course_create'),
    path('my-courses/', my_courses, name='my_courses'),
    path('my-wishlist/', wish_list, name='wishlist'),
    path('create/<course_id>/create-chapter/', course_create_chapter, name='course_create_chapter'),
    path('create/<course_id>/create-lesson/', course_create_lesson, name='course_create_lesson'),
    path('<slug>/', CoursesDetailView.as_view(), name='detail'),
    path('add_to_wishlist/<slug>/', add_to_wishlist, name='add_to_wishlist'),
]

courses/models.py
from django.conf import settings
from django.db import models
from django.contrib.contenttypes.fields import GenericRelation
from django.utils.text import slugify
from django.db.models.signals import post_save
from django.urls import reverse

from instructors.models import Instructor
from comments.models import Comment
from tags.models import Tag
from membership.models import Membership
from django.contrib.contenttypes.models import ContentType
# from rating.models import Rate

from moviepy.editor import VideoFileClip
import datetime
from time import strftime
from time import gmtime
from django.db.models import Sum

import math

SKILL_LEVEL = [
    ('all', 'All level'),
    ('beginner', 'Beginner'),
    ('intermediate', 'Intermediate'),
    ('advanced', 'Advanced'),
]




def preview_video_upload(instance, filename):
    return f'courses/{instance.title}/{instance.title}_{filename}'

def lesson_video_upload(instance, filename):
    return f'courses/lessons/{instance.title}/{instance.title}_{filename}'

def category_image_upload(instance, filename):
    return f'categories/{instance.name}/{instance.name}_{filename}'


class Category(models.Model):
    name = models.CharField(max_length=50)
    slug = models.SlugField(blank=True, null=True)
    image = models.ImageField(upload_to=category_image_upload)

    class Meta:
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('courses:category', kwargs={'slug': self.slug})

class Course(models.Model):
    title                       = models.CharField(max_length=100)
    slug                        = models.SlugField(blank=True, null=True)
    author                      = models.ForeignKey(Instructor, on_delete=models.CASCADE)
    price                       = models.DecimalField(decimal_places=2, max_digits=10)
    discount                    = models.DecimalField(decimal_places=2, max_digits=10, blank=True, null=True)
    duration                    = models.IntegerField(default=0, help_text="Type the number of minutes", blank=True, null=True)
    full_lifetime_access        = models.BooleanField(default=True)
    assignments                 = models.BooleanField(default=True)
    Certificate_of_completion   = models.BooleanField(default=True)
    preview                     = models.FileField(verbose_name="Course Video Preview", upload_to=preview_video_upload, blank=True, null=True)
    thumbnail                   = models.FileField(verbose_name="Course Thumbnial Image", upload_to=preview_video_upload)
    overview                    = models.TextField()
    description                 = models.TextField()
    what_will_learn             = models.TextField(help_text="Separate them by comman and space.")
    requirements                = models.TextField(help_text="Separate them by comman and space.")
    Skill_level                 = models.CharField(choices=SKILL_LEVEL, default='All Level', max_length=20)
    Language                    = models.CharField(max_length=100)
    best_seller                 = models.BooleanField(default=False)
    tags                        = GenericRelation(Tag)
    comments                    = GenericRelation(Comment)
    enrolled                    = models.PositiveIntegerField(default=0)
    allowed_memberships         = models.ManyToManyField(Membership, default="Free")
    category                    = models.ManyToManyField(Category)
    views                       = models.PositiveIntegerField(default=0)
    total_points                = models.PositiveIntegerField(null=True, blank=True, default=1)
    avg_points                  = models.PositiveIntegerField(null=True, blank=True, default=1)
    total_rates                 = models.PositiveIntegerField(null=True, blank=True, default=1)
    timestamp                   = models.DateTimeField(auto_now_add=True)
    updated                     = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('courses:detail', kwargs={'slug': self.slug})

    @property
    def get_rating(self):
        av = self.avg_points / self.total_points * 100
        result = "{:.1f}".format(float(av / 20))
        return float(result)

    @property
    def get_rates(self):
        av = self.avg_points / self.total_points * 100
        result = "{:.1f}".format(float(av / 20))
        r = math.floor(float(result))
        return [i for i in range(int(r))]
    
    @property
    def get_remainder(self):
        av = self.avg_points / self.total_points * 100
        result = "{:.1f}".format(float(av / 20))
        r = math.floor(float(result))
        total = 0
        for i in range(5):
            if int(r) < 5:
                total+=1
                r+=1
        return [i for i in range(int(total)) ]
        

    @property
    def get_duration(self):
        return strftime("%H:%M:%S", gmtime(float(self.duration)))

    @property
    def get_duration_hours(self):
        return strftime("%H", gmtime(float(self.duration)))

    @property
    def get_lessons_count(self):
        total = 0
        for chapter in self.chapter_set.all():
            total += int(chapter.lesson_set.all().count())
        return int(total)


    @property
    def get_price(self):
        if self.discount:
            return self.discount
        return self.price
    
    @property
    def comments_count(self):
        course_c_type = ContentType.objects.get_for_model(Course)
        comments_qs = Comment.objects.filter(content_type=course_c_type, object_id=self.id)
        return comments_qs.count()


class Chapter(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField(null=True, blank=True)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.course.title} - {self.title}'

class Lesson(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField(null=True, blank=True)
    chapter = models.ForeignKey(Chapter, on_delete=models.CASCADE, blank=True, null=True)
    position = models.IntegerField(default=1)
    duration = models.CharField(max_length=10, blank=True, null=True)
    video       = models.FileField(upload_to=lesson_video_upload)
    thumbnail = models.ImageField(upload_to=lesson_video_upload)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.chapter.title} - {self.title}'

    @property
    def get_duration(self):
        return strftime("%H:%M:%S", gmtime(float(self.duration)))


class EnrolledCourse(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    courses = models.ManyToManyField(Course)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.instructor_set.first().username

class WishList(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    courses = models.ManyToManyField(Course)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.instructor_set.first().username


# Create Slug for Course
def post_save_create_course(sender, instance, created, *args, **kwargs):
    if created:
        if instance.slug is None and instance.title:
            instance.slug = slugify(instance.title)
        instance.save()

post_save.connect(post_save_create_course, sender=Course)

# Create Slug for Category
def post_save_create_category(sender, instance, created, *args, **kwargs):
    if created:
        if instance.slug is None and instance.name:
            instance.slug = slugify(instance.name)
        instance.save()

post_save.connect(post_save_create_category, sender=Category)

# Create Slug for Chapter
def post_save_create_chapter(sender, instance, created, *args, **kwargs):
    if created:
        if instance.slug is None and instance.title:
            instance.slug = slugify(instance.title)
        instance.save()

post_save.connect(post_save_create_chapter, sender=Chapter)

# Create Slug for Lesson
def post_save_create_lesson(sender, instance, created, *args, **kwargs):
    if created:
        clip = VideoFileClip(instance.video.path)
        instance.duration = clip.duration

        chapter = instance.chapter
        course = chapter.course
        course.duration += float(clip.duration)
        course.save()

        if instance.slug is None and instance.title:
            instance.slug = slugify(instance.title)
        instance.save()

post_save.connect(post_save_create_lesson, sender=Lesson)

courses/forms.py
from django import forms
from .models import Course, Chapter, Lesson


class CourseForm(forms.ModelForm):
    class Meta:
        model = Course
        fields = ['title', 'price', 'discount', 'allowed_memberships', 'full_lifetime_access', 'assignments', 'Certificate_of_completion', 'preview', 'thumbnail', 'overview', 'description', 'what_will_learn', 'requirements', 'Skill_level', 'Language', 'category',]
        # widgets = {
        #     'title': forms.TextInput(attrs={"class" : "form-control", "id":"exampleInputEmail3",
        #                                 "placeholder":"Title"}),
        # }

    def __init__(self, *args, **kwargs):
        self._user = kwargs.pop('user')
        super(CourseForm, self).__init__(*args, **kwargs)
        li = ['full_lifetime_access', 'assignments', 'Certificate_of_completion']
        for field in self.fields:
            if field not in li:
                self.fields[field].widget.attrs['class'] = 'form-control'
                self.fields[field].widget.attrs['placeholder'] = field.title()
                if field == 'thumbnail' or field == 'preview':
                    self.fields[field].widget.attrs['style'] = 'padding: 10px'

    def save(self, commit=True):
        inst = super(CourseForm, self).save(commit=False)
        inst.author = self._user
        if commit:
            inst.save()
            self.save_m2m()
        return inst


class ChapterForm(forms.ModelForm):
    class Meta:
        model = Chapter
        fields = ['title']
        widgets = {
            'title': forms.TextInput(attrs={"class" : "form-control", "placeholder":"Title"}),
        }
    
    def __init__(self, *args, **kwargs):
        self._course = kwargs.pop('course')
        super(ChapterForm, self).__init__(*args, **kwargs)
        

    def save(self, commit=True):
        inst = super(ChapterForm, self).save(commit=False)
        inst.course = self._course
        if commit:
            inst.save()
            self.save_m2m()
        return inst



class LessonForm(forms.ModelForm):
    # _course = 1
    
    class Meta:
        model = Lesson
        exclude = ['slug', 'timestamp', 'chapter', 'duration']
    
    def __init__(self, *args, **kwargs):
        self._course = kwargs.pop('course')
        super(LessonForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'
            self.fields[field].widget.attrs['placeholder'] = field.title()
            if field == 'thumbnail' or field == 'video':
                self.fields[field].widget.attrs['style'] = 'padding: 10px'

    # def save(self, commit=True):
    #     inst = super(LessonForm, self).save(commit=False)
        
    #     if commit:
    #         inst.save()
    #         self.save_m2m()
    #     return inst
    

courses/templates/courses/course_create.html
{% extends 'base.html' %}

{% block content %}
<!-- Inner Page Breadcrumb -->
<section class="inner_page_breadcrumb">
    <div class="container">
        <div class="row">
            <div class="col-xl-6 offset-xl-3 text-center">
                <div class="breadcrumb_content">
                    <h4 class="breadcrumb_title">Create a New Course</h4>
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Create a New Course</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>
</section>

<!-- Our LogIn Register -->
<section class="our-log bgc-fa">
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <div class="login_form inner_page custom-form">
                    {{block.super}}
                    {{ form.non_field_errors }}
                    <form action="." method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="heading">
                            <h3 class="text-center">Create a New Course</h3>
                        </div>
                        {{form.as_p}}
                        <div class="form-group">
                            <label for="tags">Tags</label>
                            <input type="text" name="tags" id="tags" class="form-control">
                        </div>
                        <button type="submit" class="btn btn-log btn-block btn-thm2">Submit</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock %}

courses/templates/courses/course_create_chapter.html
 {% extends 'base.html' %}

{% block content %}
<!-- Inner Page Breadcrumb -->
<section class="inner_page_breadcrumb">
    <div class="container">
        <div class="row">
            <div class="col-xl-6 offset-xl-3 text-center">
                <div class="breadcrumb_content">
                    <h4 class="breadcrumb_title">Create a New Chapter</h4>
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Create a New Chapter</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>
</section>

<!-- Our LogIn Register -->
<section class="our-log bgc-fa">
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <div class="login_form inner_page custom-form">
                    {{block.super}}
                    <form action="." method="POST">
                        {{ forms.management_form }}
                        {% csrf_token %}
                        <div class="heading">
                            <h3 class="text-center">Create a New Chapter</h3>
                        </div>
                        <div id="form_set">
                            {% for form in forms %}
                            {{form.non_field_errors}}
                            {{form.errors}}
                            {{ form }}
                            {% endfor %}

                            <div id="empty_form" style="display:none">
                                {{ forms.empty_form }}
                            </div>
                            <input type="button" value="Add More" id="add_more"
                                class="btn dbxshad btn-lg btn-thm3 circle" style="padding: 7px 16px;
                                margin-bottom: 20px;">
                        </div>
                        <button type="submit" class="btn btn-log btn-block btn-thm2">Submit</button>
                    </form>

                </div>
            </div>
        </div>
    </div>
</section>

{% block extraScript %}
<script>
    $(document).ready(function () {
        $('#add_more').click(function () {
            var form_idx = $('#id_form-TOTAL_FORMS').val();
            $('#form_set #add_more').before($('#empty_form').html().replace(/__prefix__/g, form_idx));
            $('#id_form-TOTAL_FORMS').val(parseInt(form_idx) + 1);
        });
    });
</script>
{%endblock%}

{% endblock %}

courses/templates/courses/courses_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<style>
	.white-color {
		color: #fff;
	}
</style>

<!-- Inner Page Breadcrumb -->
<section class="inner_page_breadcrumb">
	<div class="container">
		<div class="row">
			<div class="col-xl-6 offset-xl-3 text-center">
				<div class="breadcrumb_content">
					<h4 class="breadcrumb_title">{% if title %} {{title}} {% else %} Courses {% endif %}</h4>
					<ol class="breadcrumb">
						<li class="breadcrumb-item"><a href="#">Home</a></li>
						<li class="breadcrumb-item active" aria-current="page">Courses</li>
					</ol>
				</div>
			</div>
		</div>
	</div>
</section>

<!-- Our Team Members -->
<section class="our-team pb40">
	<div class="container">
		{{block.super}}
		<div class="row">
			<div class="col-md-12 col-lg-8 col-xl-9">
				<div class="row">
					<div class="col-xl-4">
						<div class="instructor_search_result style2">
							<p class="mt10 fz15"><span class="color-dark pr10">{% if paginator %} {{paginator.count}}
									{% else %} {{courses.count}} {% endif %} </span> results <span
									class="color-dark pr10">1,236</span> Video Tutorials</p>
						</div>
					</div>
					<div class="col-xl-8">
						<div class="candidate_revew_select style2 text-right mb25">
							<ul>
								<li class="list-inline-item">
									<select class="selectpicker show-tick">
										<option>Newly published</option>
										<option>Recent</option>
										<option>Old Review</option>
									</select>
								</li>
								<li class="list-inline-item">
									<div class="candidate_revew_search_box course mb30 fn-520">
										<form class="form-inline my-2 my-lg-0" method="GET" action="{% url 'search' %}">
											<input class="form-control mr-sm-2" type="search"
												placeholder="Search our courses" aria-label="Search" name='q'>
											<button class="btn my-2 my-sm-0" type="submit"><span
													class="flaticon-magnifying-glass"></span></button>
										</form>
									</div>
								</li>
							</ul>
						</div>
					</div>
				</div>
				<div class="row">
					{% for course in courses %}
					<div class="col-lg-6 col-xl-4">
						<div class="top_courses">
							<div class="thumb">
								<a href="{{ course.get_absolute_url }}"><img class="img-whp"
										src="{{ course.thumbnail.url }}" alt="{{course.title}}"></a>
								<div class="overlay">
									{% if image.best_seller %}
									<div class="tag">Best Seller</div>
									{% endif %}
									<div class="icon"><a href="#" class="wishlist_btn"
											data-url="{% url 'courses:add_to_wishlist' slug=course.slug %}"><span
												class="fa fa-heart {% if course in request.user.wishlist.courses.all %} color-red {% else %} white-color {% endif %}"></span></a>
									</div>
									<a class="tc_preview_course" href="{{ course.get_absolute_url }}">Preview Course</a>
								</div>
							</div>
							<div class="details">
								<div class="tc_content">
									<p>{{course.author}}</p>
									<a href="{{ course.get_absolute_url }}">
										<h5>{{course.title}}</h5>
									</a>
									<ul class="tc_review">
										{% for _ in course.get_rates %}
										<li class="list-inline-item"><a href="#"><i class="fa fa-star"></i></a></li>
										{% endfor %}
										{% for _ in course.get_remainder %}
										<li class="list-inline-item"><a href="#"><i class="fa fa-star"
													style="color: #b8b6b6;"></i></a></li>
										{% endfor %}
										<li class="list-inline-item"><a href="#">({{course.total_rates}})</a></li>
									</ul>
								</div>
								<div class="tc_footer">
									<ul class="tc_meta float-left">
										<li class="list-inline-item"><a href="#"><i class="flaticon-profile"></i></a>
										</li>
										<li class="list-inline-item"><a href="#">{{course.views}}</a></li>
										<li class="list-inline-item"><a href="#"><i class="flaticon-comment"></i></a>
										</li>
										<li class="list-inline-item"><a href="#">{{course.comments_count}}</a></li>
									</ul>
									<div class="tc_price float-right">${{course.price}}</div>
								</div>
							</div>
						</div>
					</div>
					{% endfor %}
					<div class="col-lg-12">
						{% if paginator %}
						<div class="mbp_pagination">
							<ul class="page_navigation">
								{% if page_obj.has_previous %}
								<li class="page-item">
									<a class="page-link" href="?page={{ page_obj.previous_page_number }}" tabindex="-1"
										aria-disabled="true"> <span class="flaticon-left-arrow"></span> Prev</a>
								</li>
								{% endif %}
								<li class="page-item active" aria-current="page">
									<a class="page-link" href="?page={{ page_obj.number }}"
										style="color: #fff;">{{ page_obj.number }} <span
											class="sr-only">(current)</span></a>
								</li>
								{% if page_obj.has_next %}
								<li class="page-item">
									<a class="page-link" href="?page={{ page_obj.next_page_number }}">Next <span
											class="flaticon-right-arrow-1"></span></a>
								</li>
								{% endif %}
							</ul>
						</div>
						{% endif %}
					</div>
				</div>
			</div>
			<div class="col-lg-4 col-xl-3">
				<div class="selected_filter_widget style2 mb30">
					<div id="accordion" class="panel-group">
						<div class="panel">
							<div class="panel-heading">
								<h4 class="panel-title">
									<a href="#panelBodyfilter" class="accordion-toggle link fz20 mb15"
										data-toggle="collapse" data-parent="#accordion">Selected Filters</a>
								</h4>
							</div>
							<div id="panelBodyfilter" class="panel-collapse collapse show">
								<div class="panel-body">
									<div class="tags-bar style2">
										{% for cat in cats %}
										<a href="{{cat.get_absolute_url}}" style="display: inline-block;
										padding: 6px 21px;
										background: #e7e4e4;
										border-radius: 15px;"><span>{{cat.name}}</span></a>
										{% endfor %}
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
				<div class="selected_filter_widget style2">
					<div id="accordion" class="panel-group">
						<div class="panel">
							<div class="panel-heading">
								<h4 class="panel-title">
									<a href="#panelBodyAuthors" class="accordion-toggle link fz20 mb15"
										data-toggle="collapse" data-parent="#accordion">Author</a>
								</h4>
							</div>
							<div id="panelBodyAuthors" class="panel-collapse collapse show">
								<div class="panel-body">
									<div class="cl_skill_checkbox">
										<div class="content ui_kit_checkbox style2 text-left">
											{% for instructor in instructors %}
											<div class="custom-control custom-checkbox custom-checkbox-filter">
												<input type="checkbox" class="custom-control-input"
													id="customCheck{{instructor.id}}"
													onchange="filterInstructor('/search', '{{instructor.username}}');"
													{% if request.GET.search_instructor == instructor.username %}
													checked {% endif %}>
												<label class="custom-control-label" for="customCheck{{instructor.id}}"
													style="cursor: pointer;">{{instructor.username}}
													<span
														class="float-right">({{instructor.course_set.count}})</span></label>
											</div>
											{% endfor %}
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
				<div class="selected_filter_widget style2 mb30">
					<div id="accordion" class="panel-group">
						<div class="panel">
							<div class="panel-heading">
								<h4 class="panel-title">
									<a href="#panelBodyPrice" class="accordion-toggle link fz20 mb15"
										data-toggle="collapse" data-parent="#accordion">Price</a>
								</h4>
							</div>
							<div id="panelBodyPrice" class="panel-collapse collapse show">
								<div class="panel-body">
									<div class="ui_kit_whitchbox">
										<div class="custom-control custom-switch">
											<input type="checkbox" class="custom-control-input" id="customSwitch1"
												onchange="filterPrice('/search', 'Paid');"
												{% if request.GET.price == "Paid" %} checked {% endif %}>>
											<label class="custom-control-label" for="customSwitch1"
												style="cursor: pointer;">Paid </label>
										</div>
										<div class="custom-control custom-switch">
											<input type="checkbox" class="custom-control-input" id="customSwitch2"
												onchange="filterPrice('/search', 'Free');"
												{% if request.GET.price == "Free" %} checked {% endif %}>>
											<label class="custom-control-label" for="customSwitch2"
												style="cursor: pointer;">Free</label>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
				<div class="selected_filter_widget style2 mb30">
					<div id="accordion" class="panel-group">
						<div class="panel">
							<div class="panel-heading">
								<h4 class="panel-title">
									<a href="#panelBodySkills" class="accordion-toggle link fz20 mb15"
										data-toggle="collapse" data-parent="#accordion">Skill level</a>
								</h4>
							</div>
							<div id="panelBodySkills" class="panel-collapse collapse show">
								<div class="panel-body">
									<div class="ui_kit_checkbox">
										<div class="custom-control custom-checkbox">
											<input type="checkbox" class="custom-control-input" id="customCheck99"
												onchange="filterSkill('/search', 'beginner');"
												{% if request.GET.skill_level == "Beginner" %} checked {% endif %}>
											<label class="custom-control-label" for="customCheck99"
												style="cursor: pointer;">Beginner <span
													class="float-right">({{beginner.count}})</span></label>
										</div>
										<div class="custom-control custom-checkbox">
											<input type="checkbox" class="custom-control-input" id="customCheck98"
												onchange="filterSkill('/search', 'intermediate');"
												{% if request.GET.skill_level == "Intermediate" %} checked {% endif %}>
											<label class="custom-control-label" for="customCheck98"
												style="cursor: pointer;">Intermediate <span
													class="float-right">({{intermediate.count}})</span></label>
										</div>
										<div class="custom-control custom-checkbox">
											<input type="checkbox" class="custom-control-input" id="customCheck97"
												onchange="filterSkill('/search', 'advanced');"
												{% if request.GET.skill_level == "Advanced" %} checked {% endif %}>
											<label class="custom-control-label" for="customCheck97"
												style="cursor: pointer;">Advanced <span
													class="float-right">({{advanced.count}})</span></label>
										</div>
										<div class="custom-control custom-checkbox">
											<input type="checkbox" class="custom-control-input" id="customCheck96"
												onchange="filterSkill('/search', 'all');"
												{% if request.GET.skill_level == "All Level" %} checked {% endif %}>
											<label class="custom-control-label" for="customCheck96"
												style="cursor: pointer;">All Levels
												<span class="float-right">({{all.count}})</span></label>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
				<div class="selected_filter_widget style2">
					<span class="float-left"><img class="mr20" src="{% static 'images/resource/2.png' %}"
							alt="2.png"></span>
					<h4 class="mt15 fz20 fw500">Not sure?</h4>
					<br>
					<p>Every course comes with a 30-day money-back guarantee</p>
				</div>
			</div>
		</div>
	</div>
</section>

{% block extraScript %}
<script>
	function filterInstructor(url, username) {
		window.location.href = url + '/?search_instructor=' + username;
	}

	function filterPrice(url, price) {
		window.location.href = url + '/?price=' + price;
	}

	function filterSkill(url, skill) {
		window.location.href = url + '/?skill_level=' + skill;
	}
</script>

{% endblock %}
{% endblock %}